
###no args
GRAPHQL http://localhost:8082/foo/mygraphql

query {
  allMembersQuery {
    id
    firstName
    lastName
    group {
      groupId
      name
      leadName
    }
  }
}


### call query with constant
GRAPHQL http://localhost:8082/foo/mygraphql

query {
    membersByGroup(name:"first_group") {
        id
        firstName
        lastName
        group{
            groupId
            name
            leadName
        }
    }
}

### call the same query with variable
GRAPHQL http://localhost:8082/foo/mygraphql

query test($grName: String){
    membersByGroup(name: $grName){
        id
        firstName
        lastName

    }
}

{
  "grName": "second_group"
}

###mutation
GRAPHQL http://localhost:8082/foo/mygraphql

mutation createPerson($name: String, $lastName: String){
    createMember(name: $name, lastName: $lastName) {
        id
        firstName
        lastName
        group {
            name
        }
    }
}

{
  "name": "elena",
  "lastName": "pogorelova"
}
